/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.qdbus.demo.xml -i mainwindow.h -a mainwindowadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MAINWINDOWADAPTOR_H
#define MAINWINDOWADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "mainwindow.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.qdbus.server
 */
class ServerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.qdbus.server")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.qdbus.server\">\n"
"    <signal name=\"send_to_client_ok\"/>\n"
"    <signal name=\"send_to_client_error\"/>\n"
"    <method name=\"server_get\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"age\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"tel\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"adress\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"temperature\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ServerAdaptor(QObject *parent);
    virtual ~ServerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void server_get(const QString &name, int age, const QString &id, const QString &tel, const QString &adress, double temperature);
Q_SIGNALS: // SIGNALS
    void send_to_client_error();
    void send_to_client_ok();
};

#endif
