/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.qdbus.demo.xml -i mainwindow.h -a mainwindowadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mainwindowadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerAdaptor
 */

ServerAdaptor::ServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerAdaptor::~ServerAdaptor()
{
    // destructor
}

void ServerAdaptor::server_get(const QString &name, int age, const QString &id, const QString &tel, const QString &adress, double temperature)
{
    // handle method call com.qdbus.server.server_get
    QMetaObject::invokeMethod(parent(), "server_get", Q_ARG(QString, name), Q_ARG(int, age), Q_ARG(QString, id), Q_ARG(QString, tel), Q_ARG(QString, adress), Q_ARG(double, temperature));
}

